# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
    build:
        name: compilation test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run nodejs test
              run: |
                  npm run start & 
                  bash tester.sh
