# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
    build:
        name: compilation test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run test
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
              run: | # install, run server, run puppeteer script
                  npm i
                  node puppeteer.js -u $USERNAME -p $PASSWORD -h
            - name: upload result
              uses: actions/upload-artifact@v2
              with:
                  name: result
                  path: result.pdf
